# Generated by Django 3.1.1 on 2020-10-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RcContrib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_con', models.IntegerField(unique=True)),
                ('nom_con', models.CharField(max_length=255)),
                ('tipo_persona', models.CharField(choices=[('J', 'Juridica'), ('N', 'Natural'), ('G', 'Govierno')], default='J', max_length=1)),
                ('ced_rif', models.CharField(max_length=15, unique=True)),
                ('cod_edo', models.IntegerField()),
                ('cod_mun', models.IntegerField()),
                ('cod_par', models.IntegerField()),
                ('dir_cont', models.CharField(max_length=250)),
                ('telf_empresa', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('A', 'Activo'), ('P', 'Pendiente')], default='P', max_length=1)),
                ('con_acti_economica', models.IntegerField()),
                ('transeunte', models.CharField(max_length=1)),
                ('residente', models.BooleanField()),
                ('fec_inicio', models.DateField(auto_now=True)),
                ('periodo', models.IntegerField()),
                ('fec_final', models.DateField()),
                ('fax', models.CharField(max_length=25)),
                ('num_patente', models.CharField(max_length=255)),
                ('razon_comer', models.CharField(max_length=255)),
                ('fecha_inscripcion', models.DateField()),
                ('tomo', models.CharField(max_length=40)),
                ('protocolo', models.CharField(max_length=40)),
                ('tipo_empresa', models.CharField(max_length=2)),
                ('sucursal', models.CharField(choices=[('P', 'Principal'), ('S', 'Sucursal')], default='P', max_length=1)),
                ('fecha_fin_registro', models.DateField()),
                ('numero_acta', models.CharField(max_length=50)),
                ('fecha_regis_acta', models.DateField()),
                ('fecha_fin_acta', models.DateField()),
                ('correo_empresa', models.CharField(max_length=50)),
                ('correo_contacto', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(max_length=50)),
                ('fecha_fin_junta', models.DateField()),
                ('usu_reg', models.IntegerField()),
                ('usu_apro', models.IntegerField()),
            ],
        ),
    ]
