# Generated by Django 3.1.1 on 2020-10-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contribuyentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rccontrib',
            name='dir_cont',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='rccontrib',
            name='residente',
            field=models.CharField(choices=[('R', 'Residente'), ('N', 'No Residente')], default='R', max_length=1),
        ),
    ]
